


dados <- data.frame(
  codigo = c('ADM50P',
             'ADM50F',
             'ADM51F',
             'ADM51H',
             'ADM50E',
             'ADM58F',
             'ADM55F',
             'ADM53H',
             'ADM52E',
             'EPOP11',
             'ADM53E',
             'ADM58H',
             'ADM59F',
             'ADM51M',
             'ADM54E'),

  disciplina = c('ADMINISTRAÇÃO APLICADA AO PROCESSO PRODUTIVO DAS ORGANIZAÇÕES',
                 'ANÁLISE DE DADOS PARA TOMADA DE DECISÃO – ECONOMETRIA',
                 'CAPITAL MARKETS',
                 'CIÊNCIAS, TECNOLOGIA E ORGANIZAÇÕES',
                 'EMPREENDEDORISMO REGIONAL',
                 'ESG E FINANÇAS SUSTENTÁVEIS',
                 'FIXED INCOME ANALYSIS',
                 'GÊNERO, TRABALHO E DIVERSIDADE',
                 'GESTÃO DE PROJETOS - INOVAÇÃO, TECNOLOGIAS E EMPREENDEDORISMO',
                 'INDÚSTRIA 4.0: CONCEITOS E FUNDAMENTOS',
                 'LIDERANÇA HUMANIZADA',
                 'PSICOLOGIA ORGANIZACIONAL E PSICOLOGIA DO TRABALHO',
                 'ROTINAS TRABALHISTAS',
                 'SERVICE MARKETING',
                 'POLÍTICAS PÚBLICAS PARA EDUCAÇÃO, CIÊNCIA, TECNOLOGIA, INOVAÇÃO E EMPREENDEDORISMO'),

  area = c('PRODUÇÃO',
           'ECONOMIA E FINANÇAS',
           'ECONOMIA E FINANÇAS',
           'ORGANIZAÇÕES E HUMANIDADES',
           'EMPREENDEDORISMO E INOVAÇÃO',
           'ECONOMIA E FINANÇAS',
           'ECONOMIA E FINANÇAS',
           'ORGANIZAÇÕES E HUMANIDADES',
           'EMPREENDEDORISMO E INOVAÇÃO',
           'PRODUÇÃO',
           'ORGANIZAÇÕES E HUMANIDADES',
           'ORGANIZAÇÕES E HUMANIDADES',
           'ECONOMIA E FINANÇAS',
           'MARKETING E DESIGN',
           'EMPREENDEDORISMO E INOVAÇÃO'),

  ch = c(32,
         64,
         48,
         48,
         32,
         48,
         48,
         32,
         48,
         32,
         48,
         32,
         48,
         48,
         48),

  vagas = c(50,
            50,
            50,
            50,
            50,
            50,
            50,
            50,
            20,
            50,
            51,
            50,
            50,
            50,
            50),

  matriculados = c(23,
                   3,
                   24,
                   5,
                   9,
                   17,
                   22,
                   25,
                   15,
                   12,
                   47,
                   19,
                   19,
                   7,
                   0),

  docente = c('PAULO HENRIQUE DA SILVA CAMPOS',
              'MOISES DINIZ VASSALLO',
              'CLEBER GONCALVES JUNIOR',
              'CARLOS ALBERTO MAXIMO PIMENTA',
              'LUIZ EUGENIO VENEZIANI PASIN',
              'ANDRE LUIZ MEDEIROS',
              'CLEBER GONCALVES JUNIOR',
              'ISABEL CRISTINA DA SILVA ARANTES',
              'SANDRA MIRANDA NEVES',
              'MATHEUS BRENDON FRANCISCO',
              'JULIANA CAMINHA NORONHA',
              'LAUREN FERREIRA COLVARA',
              'GLEICILENE SIQUEIRA DE MELLO',
              'ELZO ALVES ARANHA',
              'DAGOBERTO ALVES DE ALMEIDA')
)
