---
title: 'RELATÓRIO DE OFERTA DE DISCIPLINAS OPTATIVAS </br> PRIMEIRO SEMESTRE DE 2023'
subtitle: 'Coordenação de Curso - Administração'
author: "**AUTOR**: *Victor Valerio* </br> **INSTITUIÇÃO**: *Instituto de Engenharia de Produção e Gestão - UNIFEI* </br> **ÚLTIMA ATUALIZAÇÃO**: *`r format(Sys.Date(), '%d-%m-%Y')`*"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{css configuracao_estilo, echo = FALSE}
.page-header {
    color: white;
    text-align: center;
    background-color: #013A71;
    background-image: linear-gradient(45deg, #8AC843, #013A71);
    padding: 1.5rem 2rem;
}

.project-tagline {
  color: white;
  text-align: center;
  margin-bottom: 2rem;
  font-weight: 400;
  opacity: 1;
  font-size: 1.5rem;
}

.project-date {
  font-weight: 400;
  opacity: 1;
  font-size: 1.2rem;
  color: white;
  text-align: center;
}

.project-author {
  font-weight: 400;
  opacity: 1;
  font-size: 1.2rem;
  color: white;
  text-align: center;
}

.main-content h1, .main-content h2, .main-content h3, .main-content h4, .main-content h5, .main-content h6 {
    margin-top: 2rem;
    margin-bottom: 1rem;
    font-weight: bold;
    color: #8AC843;
}

a {
    color: #8AC843;
    text-decoration: none;
}

.main-content table th {
    font-weight: 700;
    background-color: #013A71;
    color: white;
}
```

```{r configuracao_chunck, include = FALSE}
# CONFIGURAÇÃO DAS OPÇÕES DE CHUNK:
knitr::opts_chunk$set(cache = TRUE, 
                      message = FALSE, 
                      warning = FALSE,
                      error = FALSE,
                      echo = FALSE,
                      dpi = 600,
                      fig.align = 'center', 
                      out.width = '100%', 
                      out.height = '100%')
```

```{r pacotes}
# CARREGANDO PACOTES NECESSÁRIOS:
library(magrittr, include.only = '%>%')
library(ggplot2)
```


```{r importacao, include = FALSE}
# IMPORTAÇÃO DOS DADOS:
source('../scripts//tabela_dados.R')
```

```{r temas_graficos, include = FALSE}
# CONFIGURANDO CORES:
cor_linha_texto <- 'white'
cor_fundo <- '#013A71'
cor_barra <- '#8AC843'

# CONFIGURAÇÃO DOS TEMAS DOS GRÁFICOS:
grafico_barra_horizontal <- theme(
  axis.text.x = element_text(colour = cor_linha_texto, 
                             face = 'bold', 
                             family = 'Helvetica',
                             size = 11),
  axis.text.y = element_text(colour = cor_linha_texto, 
                             face = 'bold', 
                             family = 'Helvetica',
                             size = 11),
  axis.title.x = element_text(colour = cor_linha_texto, 
                              face = 'bold', 
                              family = 'Helvetica',
                              size = 11),
  plot.background = element_rect(fill = cor_fundo, 
                                 colour = cor_barra),
  panel.background = element_rect(fill = cor_fundo),
  panel.grid.major.x = element_line(colour = cor_linha_texto,
                                    size = 1.5),
  panel.grid.major.y = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank()) 
```

# MAPA GERAL 

```{r}
DT::datatable(dados, 
              rownames = FALSE,
              extensions = 'Buttons',
              colnames = c('CÓDIGO',
                           'DISCIPLINA',
                           'ÁREA',
                           'CH',
                           'VAGAS',
                           'MATRÍCULAS',
                           'DOCENTE'),
              options = list(pageLength = 5,
                             dom = 'Bfrtip',
                             buttons = c('excel', 'pdf'),
                             language = list(search = 'Filtrar:',
                                             paginate = c('previous' = '<',
                                                          'next' = '>'))
    ))
```

# DISCIPLINAS OFERTADAS

```{r }
g1 <- dados %>% 
  dplyr::group_by(area) %>% 
  dplyr::summarise(quantidade = dplyr::n(),
                   ch = sum(ch),
                   vagas = sum(vagas),
                   matriculados = sum(matriculados)) %>% 
  dplyr::mutate(area = forcats::fct_reorder(area, quantidade)) %>% 
  ggplot(mapping = aes(
    group = 1,
    text = paste('DISCIPLINAS OFERTADAS: ', quantidade))) + 
  geom_col(mapping = aes(x = quantidade, y = area),
           fill = '#8AC843',
           alpha = 0.9, 
           ) + 
  labs(y = '',
       x = 'DISCIPLINAS OFERTADAS') +
  theme_light() +
  grafico_barra_horizontal
  
plotly::ggplotly(g1, tooltip = c('text'))
```

# CARGA HORÁRIA

```{r }

g2 <- dados %>% 
  dplyr::group_by(area) %>% 
  dplyr::summarise(quantidade = dplyr::n(),
                   ch = sum(ch),
                   vagas = sum(vagas),
                   matriculados = sum(matriculados)) %>% 
  dplyr::mutate(area = forcats::fct_reorder(area, ch)) %>% 
  ggplot(mapping = aes(
    group = 1,
    text = paste('CARGA HORÁRIA: ', ch))) + 
  geom_col(mapping = aes(x = ch, y = area),
           fill = '#8AC843',
           alpha = 0.8) + 
  labs(y = '',
       x = 'CARGA HORÁRIA') +
  grafico_barra_horizontal

plotly::ggplotly(g2, tooltip = c('text'))
```

# VAGAS DISPONIBILIZADAS

```{r }

g3 <- dados %>% 
  dplyr::group_by(area) %>% 
  dplyr::summarise(quantidade = dplyr::n(),
                   ch = sum(ch),
                   vagas = sum(vagas),
                   matriculados = sum(matriculados)) %>% 
  dplyr::mutate(area = forcats::fct_reorder(area, vagas)) %>% 
  ggplot(mapping = aes(
    group = 1,
    text = paste('VAGAS DISPONIBILIZADAS: ', vagas))) + 
  geom_col(mapping = aes(x = vagas, y = area),
           fill = '#8AC843',
           alpha = 0.8) + 
  labs(y = '',
       x = 'VAGAS DISPONIBILIZADAS') +
  grafico_barra_horizontal

plotly::ggplotly(g3, tooltip = c('text'))
```

# ESTUDANTES MATRICULADOS

```{r }

g4 <- dados %>% 
  dplyr::group_by(area) %>% 
  dplyr::summarise(quantidade = dplyr::n(),
                   ch = sum(ch),
                   vagas = sum(vagas),
                   matriculados = sum(matriculados)) %>% 
  dplyr::mutate(area = forcats::fct_reorder(area, matriculados)) %>% 
  ggplot(mapping = aes(
    group = 1,
    text = paste('ESTUDANTES MATRICULADOS: ', matriculados))) + 
  geom_col(mapping = aes(x = matriculados, y = area),
           fill = '#8AC843',
           alpha = 0.8) + 
  labs(y = '',
       x = 'ESTUDANTES MATRICULADOS') +
  grafico_barra_horizontal

plotly::ggplotly(g4, tooltip = c('text'))
```










